#!/usr/bin/env perl
BEGIN {
    system 'juju-log Installing pre-requisites.';
    system 'sudo apt-get install -qyf cpanminus build-essential';
    system 'juju-log Installing charmkit library';
    system
      'cpanm -n https://github.com/battlemidget/App-CharmKit/archive/1.0.11.tar.gz';
}

use charm;

log 'Starting install hook for dokuwiki';

log 'Installing dependenices';
apt_update;
apt_install [
    'nginx-full', 'php-fpm',  'php-cgi',    'php-curl',
    'php-gd',     'php-json', 'php-mcrypt', 'php-readline',
    'php-mbstring'
];

my $hook_path      = path($ENV{JUJU_CHARM_DIR});
my $app_path       = path(sh('config-get app_path'));
my $app_version    = sh 'config-get app_version';
my $public_address = sh 'unit-get public-address';

$app_path->mkpath unless $app_path->exists;

sh
  'wget -q -O /tmp/dokuwiki.tgz http://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz';

sh "tar xf /tmp/dokuwiki.tgz -C $app_path --strip-components=1";

if ($app_path->child('/conf/install.php')->exists) {
    $app_path->child('/conf/install.php')->remove;
}

log "Copying template files";
sh 'cp -a templates/*.php ' . $app_path->child('conf');

my $admin_user     = sh 'config-get admin_user';
my $admin_password = sh 'config-get admin_password';
my $admin_name     = sh 'config-get admin_name';
my $admin_email    = sh 'config-get admin_email';

my $rendered =
  tpl()->render_file($hook_path->child('templates/users.auth.php'),
    $admin_user, $admin_password, $admin_name, $admin_email);
$app_path->child('conf/users.auth.php')->spew($rendered);

$rendered = tpl()->render_file($hook_path->child('templates/vhost.conf'),
    $public_address, $app_path);
my $nginx_config = path('/etc/nginx/sites-enabled/default');
$nginx_config->spew($rendered);

sh 'status-set active NGINX configured';
sh 'application-version-set ' . $app_version;

sh 'chown www-data:www-data -R ' . $app_path;

sh './hooks/stop';
sh './hooks/start';

sh 'status-set active "Dokuwiki installed and ready."';
