#!/usr/bin/env perl

use charm;

my $unit_name  = $ENV{JUJU_UNIT_NAME};

my $hook = sh 'action-get hook';
my $reportfile = "report-$hook.txt";

sh "juju-log Running self-test against $hook charm hook";
my $output = run "perl -MSmart::Comments ./hooks/$hook";
if ($? > 0) {
    sh 'action-fail Failed to run self-test';
}

file $reportfile, content => $output;

sh "action-set $hook.report='View the report with: juju run --unit $unit_name \"cat $reportfile\"'";
