#!/usr/bin/env perl

use charm;

my $unit_name  = $ENV{JUJU_UNIT_NAME};
my $reportfile = run 'action-get reportfile';

run "juju-log Will write report to $reportfile";
my $hook = run 'action-get hook';

run "juju-log Running self-test against $hook charm hook";
my $output = run "perl -MSmart::Comments ./hooks/$hook";

file "report.txt", content => $output;

if ($? > 0) {
    run 'action-fail Failed to run self-test';
}
run "action-set $hook.report='View the report with: juju run --unit $unit_name \"cat report.txt\"'";

run "juju-log self-test has finished.";
if ($exit > 0) {
    run 'action-fail Failed to run self-test.';
}
